spring:
  profiles:
    default: korea

routing-info:
  origin:
    external:
      korea: http://localhost:8081
      japan: http://localhost:8082
    internal:
      korea: http://localhost:9091
      japan: http://localhost:9092

---
spring:
  config:
    activate:
      on-profile: korea

server-info:
  region: korea

server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: japan

server-info:
  region: japan

server:
  port: 8082